spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      host: mongo.host
      port: 27017
      database: auxiliary

server:
  port: 8888

jwt:
  header: Authorization
  secret: mySecret
  expiration: 72000
  route:
    authentication:
      path: /auth
      refresh: /refresh

