spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auxiliary?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: root
    password: djuey2eh8u

server:
  port: 8888

jwt:
  header: Authorization
  secret: mySecret
  expiration: 72000
  route:
    authentication:
      path: /auth
      refresh: /refresh

